- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Import VPC variables
    include_vars: vars/vpc_setup.txt
  - name: Creating VPC  
    ec2_vpc_net:
            name: "{{vpc_name}}"
            region: "{{region}}"
            cidr_block: "{{vpc_cidr}}"
            tenancy: default
            dns_hostnames: yes
            dns_support: yes
            state: "{{state}}"
    register: vpcout
  - name: Creating public subnet in VPC in zone1
    ec2_vpc_subnet: 
       vpc_id: "{{vpcout.vpc.id}}"
       state: "{{state}}"
       cidr: "{{PubSub1Cidr}}"
       region: "{{region}}"
       az: "{{zone1}}"
       map_public: yes
       resource_tags:
               Name: vprofile-pubsub1
    register: pubsub1out
  - name: Creating public subnet in VPC in zone2
    ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       state: "{{state}}"
       cidr: "{{PubSub2Cidr}}"
       region: "{{region}}"
       az: "{{zone2}}"
       map_public: yes
       resource_tags:
               Name: vprofile-pubsub2
    register: pubsub2out
  - name: Creating public subnet in VPC in zone3
    ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       state: "{{state}}"
       cidr: "{{PubSub3Cidr}}"
       region: "{{region}}"
       az: "{{zone3}}"
       map_public: yes
       resource_tags:
               Name: vprofile-pubsub3
    register: pubsub3out
  - name: Creating private subnet in VPC in zone1
    ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        cidr: "{{PriSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        resource_tags:
              Name: vprofile-prisub1
    register: prisub1out
  - name: Creating private subnet in VPC in zone2
    ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        cidr: "{{PriSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        resource_tags:
              Name: vprofile-prisub2
    register: prisub2out
  - name: Creating private subnet in VPC in zone3
    ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        cidr: "{{PriSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        resource_tags:
             Name: vprofile-prisub3
    register: prisub3out
  - name: Create Internet gateway
    amazon.aws.ec2_vpc_igw:
      vpc_id: "{{vpcout.vpc.id}}"
      state: "{{state}}"
      region: "{{region}}"
      resource_tags:
              Name: IGW
    register: igwout
  - name: Creating Public Subnet Route table
    amazon.aws.ec2_vpc_route_table:
            vpc_id: "{{vpcout.vpc.id}}"
            state: "{{state}}"
            region: "{{region}}"
            tags:
              Name: Vprofile-Pub
            subnets:
               - "{{pubsub1out.subnet.id}}"
               - "{{pubsub2out.subnet.id}}"
               - "{{pubsub3out.subnet.id}}"
            routes:
               - dest: 0.0.0.0/0
                 gateway_id: "{{igwout.gateway_id}}"
    register: pub_RTout
  - name: Creating a NAT Gateway and allocate new EIP if a nat gateeway does not exists in the subnet.
    ec2_vpc_nat_gateway:
            state: "{{state}}"
            subnet_id: "{{pubsub1out.subnet.id}}"
            wait: yes
            region: "{{region}}"
            if_exist_do_not_create: true
    register: natgwout
  - name: Creating Private Subnet Route table
    ec2_vpc_route_table:
            vpc_id: "{{vpcout.vpc.id}}"
            state: "{{state}}"
            region: "{{region}}"
            tags:
              Name: Vprofile-PriRT
            subnets:
              - "{{prisub1out.subnet.id}}"
              - "{{prisub2out.subnet.id}}"
              - "{{prisub3out.subnet.id}}"
            routes:
              - dest: 0.0.0.0/0
                gateway_id: "{{natgwout.nat_gateway_id}}"
    register: pri_RTout
  - name: Printing the required variables
    debug:
            var: "{{item}}"
    loop:
           - vpcout.vpc.id
           - pubsub1out.subnet.id
           - pubsub2out.subnet.id
           - pubsub3out.subnet.id
           - prisub1out.subnet.id
           - prisub2out.subnet.id
           - prisub3out.subnet.id
           - igwout.gateway_id
           - pub_RTout.route_table.id
           - natgwout.nat_gateway_id
           - pri_RTout.route_table.id
  - name: Transferring variables to a file
    copy:
            content: "region: {{region}}\nvpcid: {{vpcout.vpc.id}}\npubsub1id: {{pubsub1out.subnet.id}}\npubsub2id: {{pubsub2out.subnet.id}}\npubsub3id: {{pubsub3out.subnet.id}}\nprisub1id: {{prisub1out.subnet.id}}\nprisub2id: {{prisub2out.subnet.id}}\nprisub3id: {{prisub3out.subnet.id}}\nigwid: {{igwout.gateway_id}}\npubRTid: {{pub_RTout.route_table.id}}\nNATgwid: {{natgwout.nat_gateway_id}}\npriRTid: {{pri_RTout.route_table.id}}\n"
            dest: ./vars/output_vars.txt
